In [1]:
import torch

a = torch.tensor(3)
b = torch.tensor([1, 2, 3])
c = torch.tensor([[1, 2, 3],[4, 5, 6]])

print(a)
print(b)
print(c)

tensor(3)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [2]:
import torch

x = torch.tensor([[1, 2, 3],[4, 5, 6]])

print(x.shape)   # torch.Size([2, 3])
print(x.ndim)    # 2
print(x.numel()) # 6

torch.Size([2, 3])
2
6


In [3]:
zeros = torch.zeros(2, 3)
ones = torch.ones(2, 3)
randn = torch.randn(2, 3)   # 标准正态分布随机数
rand = torch.rand(2, 3)     # 0~1 均匀分布

print(zeros)
print(ones)
print(randn)
print(rand)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.7739, -1.0782,  0.8209],
        [-0.7492, -0.4648,  2.2757]])
tensor([[0.3320, 0.8378, 0.6802],
        [0.1666, 0.5471, 0.9917]])


In [4]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)
print(x.dtype)

torch.float32


In [5]:
import torch

a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

tensor([5., 7., 9.])
tensor([-3., -3., -3.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])


In [6]:
x = torch.tensor([[1., 2.],[3., 4.]])
y = torch.tensor([[5., 6.],[7., 8.]])

print(x * y)        # 逐元素乘法
print(x @ y)        # 矩阵乘法
print(torch.matmul(x, y))

tensor([[ 5., 12.],
        [21., 32.]])
tensor([[19., 22.],
        [43., 50.]])
tensor([[19., 22.],
        [43., 50.]])


In [7]:
x = torch.tensor([10, 20, 30, 40])

print(x[0])   # 10
print(x[2])   # 30
print(x[-1])  # 40

tensor(10)
tensor(30)
tensor(40)


In [9]:
x = torch.tensor([[1, 2, 3],
                [4, 5, 6]])

print(x[0])      # 第 0 行
print(x[1])      # 第 1 行
print(x[0, 1])   # 第 0 行第 1 列 => 2

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor(2)


In [10]:
x = torch.tensor([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(x[:, 0])    # 第 0 列
print(x[0:2, :])  # 前两行
print(x[:, 1:3])  # 第 1 到第 2 列

tensor([1, 4, 7])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])


In [11]:
x = torch.arange(12)
print(x)
print(x.shape)   # [12]

y = x.reshape(3, 4)
print(y)
print(y.shape)   # [3, 4]

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [12]:
x = torch.arange(12)

y = x.reshape(3, -1)
print(y.shape)   # [3, 4]

z = x.reshape(2, -1)
print(z.shape)   # [2, 6]

torch.Size([3, 4])
torch.Size([2, 6])


In [13]:
x = torch.tensor([1, 2, 3])
print(x.shape)   # [3]

y = x.unsqueeze(0)
print(y.shape)   # [1, 3]

z = x.unsqueeze(1)
print(z.shape)   # [3, 1]

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


In [14]:
x = torch.tensor([[1, 2, 3]])
print(x.shape)   # [1, 3]

y = x.squeeze()
print(y.shape)   # [3]

torch.Size([1, 3])
torch.Size([3])


In [15]:
x = torch.randn(2, 3)
print(x.shape)   # [2, 3]

y = x.transpose(0, 1)
print(y.shape)   # [3, 2]

torch.Size([2, 3])
torch.Size([3, 2])


In [16]:
x = torch.randn(2, 3, 4)
print(x.shape)   # [2, 3, 4]

y = x.permute(2, 0, 1)
print(y.shape)   # [4, 2, 3]

torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


In [17]:
img = torch.randn(224, 224, 3)
img = img.permute(2, 0, 1)
print(img.shape)   # [3, 224, 224]

torch.Size([3, 224, 224])


In [18]:
x = torch.tensor([1.0, 2.0, 3.0])
y = 2.0

print(x + y)

tensor([3., 4., 5.])


In [19]:
a = torch.randn(2, 3)
b = torch.randn(3)

print((a + b).shape)   # [2, 3]

torch.Size([2, 3])


In [20]:
a = torch.randn(2, 3)
b = torch.randn(2, 1)

print((a + b).shape)   # [2, 3]

torch.Size([2, 3])


In [21]:
import torch

# 1. 创建张量
x = torch.arange(12)
print("x =", x)
print("x.shape =", x.shape)

# 2. reshape
y = x.reshape(3, 4)
print("\ny =", y)
print("y.shape =", y.shape)

# 3. 索引
print("\ny[0] =", y[0])
print("y[1, 2] =", y[1, 2])
print("y[:, 1] =", y[:, 1])

# 4. unsqueeze / squeeze
z = torch.tensor([1, 2, 3])
print("\nz.shape =", z.shape)

z1 = z.unsqueeze(0)
print("z.unsqueeze(0).shape =", z1.shape)

z2 = z.unsqueeze(1)
print("z.unsqueeze(1).shape =", z2.shape)

print("z2.squeeze().shape =", z2.squeeze().shape)

# 5. permute
a = torch.randn(2, 3, 4)
print("\na.shape =", a.shape)
b = a.permute(2, 0, 1)
print("b.shape =", b.shape)

# 6. broadcasting
m = torch.randn(2, 3)
n = torch.randn(3)
print("\nm.shape =", m.shape)
print("n.shape =", n.shape)
print("(m + n).shape =", (m + n).shape)

x = tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
x.shape = torch.Size([12])

y = tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
y.shape = torch.Size([3, 4])

y[0] = tensor([0, 1, 2, 3])
y[1, 2] = tensor(6)
y[:, 1] = tensor([1, 5, 9])

z.shape = torch.Size([3])
z.unsqueeze(0).shape = torch.Size([1, 3])
z.unsqueeze(1).shape = torch.Size([3, 1])
z2.squeeze().shape = torch.Size([3])

a.shape = torch.Size([2, 3, 4])
b.shape = torch.Size([4, 2, 3])

m.shape = torch.Size([2, 3])
n.shape = torch.Size([3])
(m + n).shape = torch.Size([2, 3])
